EXEC sp_resetstatus 'Dbname';

ALTER DATABASE Dbname SET EMERGENCY

DBCC checkdb('Dbname')

ALTER DATABASE Dbname SET SINGLE_USER WITH ROLLBACK IMMEDIATE

DBCC CheckDB ('Dbname', REPAIR_ALLOW_DATA_LOSS)

ALTER DATABASE Dbname SET MULTI_USER